FROM alpine:3.19.1

USER root

ARG GROUP_ID=1011
ARG USER_ID=1011

RUN apk update && \
    apk add openjdk17

RUN addgroup --system --gid ${GROUP_ID} testgroup
RUN adduser --system --uid ${USER_ID} testuser --ingroup testgroup

USER testuser

COPY ../build/libs/spring-boot-0.0.1-SNAPSHOT.jar ./spring-boot-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/spring-boot-0.0.1-SNAPSHOT.jar"]